# Generated by Django 4.2 on 2023-07-20 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_service_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='services',
            new_name='service',
        ),
    ]
