# Generated by Django 4.2 on 2023-07-20 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_images_image_rename_services_image_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
