# Generated by Django 4.2 on 2023-07-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='back_graound',
            name='name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
