# Generated by Django 4.2.3 on 2023-07-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_tag_post_post_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hindi_description',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
